//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        public int UserId { get; set; }
        public int StatusId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string ChangeUserId { get; set; }
        public System.DateTime ChangeDate { get; set; }
    
        public virtual Lookup Lookup { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
