//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long LogId { get; set; }
        public int LogTypeId { get; set; }
        public string Descr { get; set; }
        public string URL { get; set; }
        public string Page { get; set; }
        public string LinkToId { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual Lookup Lookup { get; set; }
    }
}
