//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookup
    {
        public Lookup()
        {
            this.AppUser = new HashSet<AppUser>();
            this.Log = new HashSet<Log>();
        }
    
        public int LookupId { get; set; }
        public int LookupTypeId { get; set; }
        public string Descr { get; set; }
        public string Value { get; set; }
        public Nullable<int> Sequence { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<AppUser> AppUser { get; set; }
        public virtual ICollection<Log> Log { get; set; }
        public virtual LookupType LookupType { get; set; }
    }
}
