//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupType
    {
        public LookupType()
        {
            this.Lookup = new HashSet<Lookup>();
        }
    
        public int LookupTypeId { get; set; }
        public string Descr { get; set; }
    
        public virtual ICollection<Lookup> Lookup { get; set; }
    }
}
